### ISSUE TITLE
Why hyphenated name?

### ISSUE THREAD

**Issue by anselmbradford** [Timgur/gifv#4]
@Timgur Sweet! This looks great. Just curious, why `<gif-v ... />` and not `<gifv ... />`? Hyphenated html elements are most unusual, but then again web components are their own animal.

**Comment by Timgur** [comment]
@anselmbradford seems that in order to be a valid web component that the dash is needed :(

**Comment by anselmbradford** [comment]
@Timgur Ahh so if can be namespaced, etc. Got it! TIL
